name: vtxcnn
channels:
  - defaults
  - conda-forge
dependencies:
  - awkward=0.12.20
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - blas=1.0
  - cmake=3.14.0
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - glib=2.63.1
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - anaconda::keras=2.3.1
  - krb5=1.16.4
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.11.4
  - matplotlib=3.1.3
  - numpy=1.16.4
  - pandas=1.0.1
  - protobuf=3.11.4
  - python=3.7.6
  - pyyaml=5.3
  - qt=5.9.7
  - readline=8.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - setuptools=45.2.0
  - sqlite=3.31.1
  - anaconda::tensorboard=1.13.1
  - anaconda::tensorflow=1.13.1
  - yaml=0.1.7
  - conda-forge::uproot=3.11.3
  - conda-forge::root=6.18.00
  
